server:
  port: 8085
hm:
  db:
    database : hm-trade
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
